#ifndef LEX_TYPE
#define LEX_TYPE
#include <iostream>

enum lexem_type {
	LEX_NULL, LEX_AND, LEX_BEGIN, LEX_BOOL, LEX_DO, 
	LEX_ELSE, LEX_END, LEX_IF, LEX_FALSE, LEX_INT,
       	LEX_NOT, LEX_OR, LEX_PROGRAM, LEX_READ, LEX_THEN,
	LEX_TRUE, LEX_VAR, LEX_WHILE, LEX_WRITE, LEX_FIN,
	LEX_SEMICOLON, LEX_STRING, LEX_COMMA, LEX_COLON,
       	LEX_ASSIGN, LEX_LPAREN, LEX_RPAREN, LEX_LFIGURE, 
	LEX_RFIGURE, LEX_EQ, LEX_LSS, LEX_GTR, LEX_PLUS,
       	LEX_MINUS, LEX_TIMES, LEX_SLASH, LEX_LEQ, LEX_NEQ,
       	LEX_GEQ, LEX_NUM, LEX_ID, POLIZ_LABEL, POLIZ_ADDRESS,
       	POLIZ_GO, POLIZ_FGO
};
#endif
